---
title: 'Syllabus Fall 2021 \linebreak Marketing 4050 - Marketing Research' 
output:
  pdf_document: default
  html_notebook: default
---

Instructor: Mike Nguyen

Office: : 417 Cornell Hall

Email: [mikenguyen\@mail.missouri.edu](mailto:mikenguyen@mail.missouri.edu){.email}

Class Hours:

Office Hours: By appointment

# Textbooks

*Basic Marketing Research*, Brown, Suter, and Churchill, 9th ed., 2018, Cengage (required)

Course packet, College of Business Copy Center (required---will be used in almost every class meeting)

[Auto-access Trouble Shoot](https://github.com/mikenguyen13/mar4050_F21/raw/master/Autoaccess_troubleshoot.docx)

<br>

# Course Objectives

This course will provide students with an understanding of the role of marketing research in organizations and knowledge about how marketing research is carried out. Students will learn the language of marketing research, the value of primary and secondary sources of data, and how errors in research can be reduced or avoided. The course is also designed to further students' professional development by enhancing their ability to:

-   solve business problems

-   effectively communicate facts and opinions

-   work in groups

-   manage time and tasks effectively

-   make effective formal presentations

<br>

## **Prerequisites**

Mktg 3000, junior standing, and Statistics 3500

<br>

## Knowledge objectives (topical coverage)

The following topics must be covered in the course, and students should be able to demonstrate knowledge of key principles in each topic.

-   The marketing research process

-   Marketing research industry structure

-   Sources of information (primary, secondary, syndicated)

-   Problem definition and exploratory research

-   Research design options (qualitative, causal, survey)

-   Data collection methods

-   Measurement (levels of measurement, types of measurement scales)

-   Questionnaire design

-   Sampling methods and sampling plans

-   Fieldwork and data quality; data preparation and coding

-   Descriptive statistical analysis (mean, median, mode; frequency distribution; cross-tabulation)

-   Basic data visualization

-   Correlation and regression applications

-   Oral and written presentation of results

<br>

## Performance objectives

Students will be asked to demonstrate their ability to do the following activities.

Students, with the assistance of group members, will be able to conduct and complete small-scale marketing research project, including problem definition, questionnaire design, sample design, data collection, data analysis, and project oral and written report.

Students will be able to calculate the following statistics in Excel, be able to interpret them, and know the proper data visualization techniques to present the results:

-   mean

-   percentages and frequency distribution

-   cross-tabulation

Students will be able to interpret correlation and regression results, including slope coefficients and model fit.

<br>

## Student Evaluation

| Components                     | Points |
|--------------------------------|--------|
| Exam (2)                       | 500    |
| Group Term Project Assignments | 200    |
| Group Case Presentation        | 50     |
| Attendance                     | 40     |
| Participation                  | 50     |
| Professionalism                | 10     |
| In-class Quiz                  | 50     |
| Individual Assignments         | 100    |
| Total                          | 1000   |

Extra Credit: 3-5%

<br>

## Examinations

Examinations will consist of

-   multiple choice

-   short essay questions

-   problems.

Makeup exams will be given only in cases of verified illness or in other extenuating circumstances approved at least one week beforehand by the instructor. Makeup exams are normally given during final exam week. An unexcused absence from an exam will result in a grade of zero for that exam.

<br>

## Group Term Project

The group project is a small-scale marketing research project and includes problem definition, questionnaire design, data collection, data analysis, and writing up the research report. Each group will also give an oral presentation at the end of the semester. Group members will evaluate each other's performance on the project, and the evaluation will be considered in assigning individual students' grades for the project. If a group member consistently fails to contribute appropriately to the group's work, the other group members may request in writing to the instructor that the non-performing member be terminated from group. In such instances, the terminated group member will be allowed to use data collected by the group but will be required to complete remaining project assignments on his/her own, including data analysis, presentation, and final report. A terminated group member may appeal this decision to the instructor in writing, but must do so within **four calendar days of notice of dismissal**.

Project Assignment (PA) Document

Sample term project report

<br>

## Attendance, Participation, and Professionalism

-   This class meets in-person at the scheduled time slot. Students are expected to be present at all class sessions and to participate by asking and answering questions at multiple points during each class session. In other words, attendance is **mandatory**. Failure to do so will result in loss of class participation and attendance points.  Both quality and quantity of contributions are considered in assigning the class participation grade.

-   To be excused due to illness, the student must either notify the professor before class of the illness, or provide the instructor with **a doctor's note**.

-   [Be on time to class]{.ul}. Important material is covered in the first few minutes of class. Students who are late to class will lose attendance points.

-   Students are expected to be prepared and to read assigned discussion cases before class begins. They are also expected to pay attention in class, and they will be called upon to present their views on class material and discussion cases. Students are also expected to contribute to the class by asking questions. Both quality and quantity of contributions are considered in assigning the class participation grade**.**

-   Professional behavior is expected of all students. Professionalism includes being on time, being courteous to class members and the instructor, being reliable and conscientious when working on group projects, and other aspects of behavior normally expected of students or employees.

-   **Important note on attendance:** Everyone is allowed to have **two** absences without questions asked. After that each absence will cost you 50% of the attendance score unless excused by the professor. Thus, **on your fourth absence**, all your attendance points will be gone. For example, when you miss two classes, your attendance won't be affected. when you miss the third class, you attendance point is now only 20. when you miss the fourth class, you will receive 0 in your attendance point. **Attendance points are recorded by iClicker.**

-   **Import note on participation**: Your participation points are also recorded by **iClicker in class polls**. Students who are late to class will be marked **absent**. The start and end times for the class are determined by the classroom clock, not the time on students' phones.

-   **Import note on professionalism**:Students are expected to act in a professional manner during the class. If over half of your group members rate your performance as poor, professionalism point will automatically be 0. Professionalism includes being on time, being courteous to class members and
    the instructor, being reliable and conscientious when working on group projects, and other aspects of behavior normally expected of students or employees.

<br>

## Assignments

-   Assignments are to be turned in using Canvas and are due at the time noted on Canvas.

-   Late assignments are eligible for up to 50% of total points if they are turned in with 24 hours of the due date; after that, no credit will be given for late assignments. To be considered, any requests to re-grade an assignment must be made within one week after the grade has been posted on Canvas.

-   ***Project Assignments*** (PA) are described in the course packet immediately following the syllabus. They are to be completed by group members and turned in on the due dates shown. To be considered, any requests to re-grade an assignment must be made within one week after the grade has been posted on Canvas.

-   ***Discussion Cases*** are [individual]{.ul} exercises to be completed on your own and form the basis for our class discussions. They need to be completed before class meets, and you will be called upon at various times throughout the semester to discuss your work on these exercises. Your work on these exercises will not be collected, but if you're unable to discuss your work when called upon, your participation grade will be negatively affected.

    -   Case Discussion Document

<br>

# Academic Honesty

Academic honesty is fundamental to the activities and principles of a university. All members of the academic community must be confident that each person's work has been responsibly and honorably acquired, developed, and presented. Any incident of academic honesty (such as cheating on tests or plagiarism) will be reported to the office of the provost. Academic dishonesty is an extremely serious matter with serious consequences, potentially including an automatic F for the course and probation or expulsion.

<br>

# Special Needs

If you have special needs as addressed by the Americans with Disabilities Act and need assistance, you must notify the instructor by the second week of the semester. To request academic accommodations, students must also register with Disability Services, AO38 Brady Commons, 882-4696. It is the campus office responsible for reviewing documentation provided by students requesting academic accommodations, and for accommodations planning in cooperation with students and instructors, as needed and consistent with course requirements.

<br>

# Policy on Discrimination 

*We have **no tolerance** for discrimination or acts of hate in our community and encourage robust, respectful dialogue and interactions. No matter where you come from, no matter your race, gender, identity, preference or idea & perspective, we all come together to learn, and everyone deserves to be treated with respect and to thrive. If anyone experiences discrimination or harassment, we encourage them to report it to our campus [Offices of Civil Rights](https://www.umsystem.edu/ums/dei/titleix/title_ix_offices) and Title IX at civilrights-titleix\@missouri.edu.*

<br>

# **Decreasing the Risk of COVID-19 in Classrooms and Labs**

MU cares about the health and safety of its students, faculty, and staff. To provide safe, high-quality education amid COVID-19, we will follow several specific campus policies in accordance with the advice of the Center for Disease Control and Boone County health authorities. This statement will be updated as information changes.

-   **If you are experiencing any COVID-related symptoms,** or are otherwise feeling unwell, do not attend in-person classes and contact your health care provider and/or student health immediately. COVID symptoms include: fever greater than 100.4 or chills; cough, shortness of breath or difficulty breathing; fatigue; unexplained muscle or body aches; headache; new loss of taste or smell; sore throat; congestion or runny nose; nausea or vomiting; diarrhea.

-   We will all wear **face coverings while in the classroom**, unless you have a documented exemption due to a disability or medical condition.

-   We will maintain a **6-foot distance from each other at all times** (except in specific lab/studio courses with other specific guidelines for social distancing).

-   We will enter the classroom and **fill the room starting at the front, filing all the way across a row**. When class ends, we will exit the row nearest to the door first; the instructor or TA will give the signal for the next row to exit, in the same manner.

-   In any small section or lab class that requires them, **additional measures will be listed in the syllabus and be mandatory for class participation**.

-   Online office hours will be available for all students.

Compliance with these guidelines is required for all; anyone who fails to comply will be subject to the[ accountability process](https://accountability.missouri.edu/accountability/conduct-process/), as stated in the University's[ Collected Rules and Regulations](https://www.umsystem.edu/ums/rules/collected_rules/programs/ch200), Chapter 200 Student Code of Conduct.

If an instructor has concerns about how a student is following COVID-19 policies and protocols, please report those concerns to the Office of the Dean of Students. You can fill out a COVID Safety Measures Reporting Form here:[ https://cm.maxient.com/reportingform.php?UnivofMissouriSystem&layout_id=38](https://cm.maxient.com/reportingform.php?UnivofMissouriSystem&layout_id=38)

By taking the above measures, we are supporting your health and that of the whole Mizzou community. Thank you in advance for joining me and your peers in adhering to these safety measures.

<br>

# **SCHEDULE -- MRKTNG 4050**

**Import note:**

-   All of the course materials are published on Canvas

-   Alternatively, you can also access the materials via my online repository

+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
|    | **Date** | **Topic**                                         | **Assignments Due**                         | **Reading**  |
+:==:+==========+===================================================+=============================================+==============+
| 1  | Aug 24   | Course Intro; Problem Analysis                    |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 2  | Aug 26   | The Research Process                              | Project Review Assign; PA \#1 due 5 pm      | Ch. 1        |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 3  | Aug 31   | Problem Definition; Intro to Project              | Discussion case \#1 (p. 3-1)                | Chs. 2, 3    |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 4  | Sep   2  | Research Designs                                  | PA \#2; Discussion case \#2 (p. 4-1)        | Chs. 4       |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
|    | Sep   7  | Labor Day                                         |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 5  | Sep   9  | Information Systems, Dashboards, & Data Analytics | Discussion case \#3 (p. 5-1) & \#4 (p. 5-3) | Chs. 5, 6    |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 6  | Sep 14   | Secondary & Syndicated Data                       | PA \#3; Project Meetings: Sign-up here      | Ch. 7        |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 7  | Sep 16   | Experimentation; Project Meetings                 |                                             | Ch. 8        |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 8  | Sep 21   | Survey Research                                   | Discussion case \#5 (p. 7-1)                | Chs. 9, 11   |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 9  | Sep 23   | Measurement; Questionnaire Design                 | Discussion case \#6 (p. 8-1); Qualtrics     | Ch. 12       |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 10 | Sep 28   | Questionnaire Design II                           |                                             | Ch. 13       |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 11 | Sep 30   | Questionnaire Analysis                            | PA \#4                                      |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 12 | Oct   5  | Sampling; Data Preparation                        | Discussion case \#7 (p. 12-1)               |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 13 | Oct   7  | Project Meetings                                  | PA \#5, PA \#6                              | Ch. 14, 15\* |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 14 | Oct 12   | **First Exam**                                    |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 15 | Oct 14   | Work Day (collecting data)                        | PA \#7                                      | Ch. 16       |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 16 | Oct 19   | Descriptive Statistics                            |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 17 | Oct 21   | Data Analysis Plans                               | PA \#8 & PA \#9                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 18 | Oct 26   | Data Analysis                                     | PA \#10 & PA \#11                           |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 19 | Oct 28   | Visualizing and Reporting Data                    |                                             | Ch. 20       |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 20 | Nov   2  | Correlation, Simple Regression                    | PA \#12                                     |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 21 | Nov   4  | Simple Regression (continued)                     | Discussion case \#8 (p. 21-1)               |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 22 | Nov   9  | Multiple Regression Basics                        | Opinion Outpost Assign (optional)           |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 23 | Nov 11   | Multiple Regression Applications                  | Zoom presentation practice (extra credit)   |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 24 | Nov 16   | Project Meetings                                  | PA \#13 (optional; sign up by 11/15)        |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 25 | Nov 18   | Presentations                                     | PA \#14, PA \#15                            |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
|    |          | Thanksgiving Break                                |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 26 | Nov 30   | Presentations                                     | PA \#14, PA \#15                            |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 27 | Dec   2  | Review for Exam                                   |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 28 | Dec   7  | **Second Exam**                                   |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 29 | Dec   9  | Project Checkup                                   |                                             |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+
| 30 | Dec 14   | Project Report Due                                | PA \#16 & PA \#17                           |              |
+----+----------+---------------------------------------------------+---------------------------------------------+--------------+

**NOTE**: PA is a group project assignment. Assignment page numbers refer to pages in the course packet; chapters refers to chapters in the textbook.

\*Skip pp. 231-233 in Ch. 15; refer to the Canvas document titled Response Rates to replace this material.

# Additional Policy and Information

## **IClicker Reef**

-   Please create an account on iClicker App in Apple or Android store with your full name on the Myzou. If you don't have a smart phone, you can do so through desktop version.

-   Once you have successfully downloaded the app and signed in, search for "University of Missouri Columbia"

-   Then search for "**Marketing Research 4050 "** for your course. And select the course by "**Mike Nguyen**"

-   Click **"Add This Course".**

-   You attendance, in class participation, and quiz will be done through the iClicker.

-   
